// ffollow.h
// *** DO NOT EDIT BY HAND ***
// automatically generated by elkhound, from ffollow.gr

#ifndef FFOLLOW_H
#define FFOLLOW_H

#include "useract.h"     // UserActions


// parser context class
class 
#line 13 "ffollow.gr"
 Context : public UserActions {
#line 16 "ffollow.h"


private:
  USER_ACTION_FUNCTIONS      // see useract.h

  // declare the actual action function
  static SemanticValue doReductionAction(
    Context *ths,
    int productionId, SemanticValue const *semanticValues,
  SourceLoc loc);

  // declare the classifier function
  static int reclassifyToken(
    Context *ths,
    int oldTokenType, SemanticValue sval);

  void action0___EarlyStartSymbol(SourceLoc loc, SemanticValue top);
  void action1_S(SourceLoc loc);
  void action2_E(SourceLoc loc);
  void action3_Ep(SourceLoc loc);
  void action4_Ep(SourceLoc loc);
  void action5_T(SourceLoc loc);
  void action6_Tp(SourceLoc loc);
  void action7_Tp(SourceLoc loc);
  void action8_F(SourceLoc loc);
  void action9_F(SourceLoc loc);

// the function which makes the parse tables
public:
  virtual ParseTables *makeTables();
};

#endif // FFOLLOW_H
